version: '3.8'

services:
  java:
    build: .
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server/src:/usr/src:cached
    env_file:
      - ./javaenvfile.env
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=web_java
      - POSTGRES_USER=bc
      - POSTGRES_PASSWORD=2068686
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

volumes:
  db-data:
