```mermaid
erDiagram

users ||--o{ articles: ""

users {
  integer id
  varchar(10) password
  varchar(40) name
}

books {
  integer id
	varchar(100) title
	varchar(40) author
	boolean isBorrowed
	date start_date
	date end_date
}
```